// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuadMasterApp.Data;

#nullable disable

namespace QuadMasterApp.Migrations
{
    [DbContext(typeof(TournamentContext))]
    partial class TournamentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("QuadMasterApp.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("QuadMasterApp.Data.Models.Quad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuadGroupNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Quads");
                });

            modelBuilder.Entity("QuadMasterApp.Data.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormattedAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("QuadMasterApp.Data.Models.TournamentPlayer", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuadPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Round1Opponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Round1Score")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Round1Table")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Round2Opponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Round2Score")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Round2Table")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Round3Opponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Round3Score")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Round3Table")
                        .HasColumnType("INTEGER");

                    b.HasKey("TournamentId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuadId");

                    b.ToTable("TournamentPlayers");
                });

            modelBuilder.Entity("QuadMasterApp.Data.Models.Quad", b =>
                {
                    b.HasOne("QuadMasterApp.Data.Models.Tournament", "Tournament")
                        .WithMany("Quads")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("QuadMasterApp.Data.Models.TournamentPlayer", b =>
                {
                    b.HasOne("QuadMasterApp.Data.Models.Player", "Player")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuadMasterApp.Data.Models.Quad", "Quad")
                        .WithMany("Players")
                        .HasForeignKey("QuadId");

                    b.HasOne("QuadMasterApp.Data.Models.Tournament", "Tournament")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Quad");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("QuadMasterApp.Data.Models.Player", b =>
                {
                    b.Navigation("TournamentPlayers");
                });

            modelBuilder.Entity("QuadMasterApp.Data.Models.Quad", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("QuadMasterApp.Data.Models.Tournament", b =>
                {
                    b.Navigation("Quads");

                    b.Navigation("TournamentPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
